# See documentation at https://goreleaser.com
before:
  hooks:
    - go mod download
builds:
  - id: powershell-connector
    binary: powershell-connector
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      - linux
      - windows
    ldflags:
      - >-
        -s -w -X main.version={{.Version}}
        -X main.commit={{.Commit}}
        -X main.date={{.CommitDate}}
release:
  draft: true
  github:
    owner: NETWAYS
archives:
  - format: binary
    replacements:
      linux: Linux
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Version }}-SNAPSHOT-{{.ShortCommit}}'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^goreleaser:'
